<Project>
  <Import Project="..\Directory.Build.props" />

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(Configuration)' == 'Release'">net8.0;net9.0;$(TargetFrameworks)</TargetFrameworks>

    <IsPackable>false</IsPackable>
    <NoWarn>CA2007;$(NoWarn)</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="$(ProjectName.EndsWith('Tests'))">
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup Condition="$(ProjectName.EndsWith('Tests'))">
    <Compile Include="$(MSBuildThisFileDirectory)AssemblyInfo.cs" Link="AssemblyInfo.cs" />

    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />

    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'" >
    <PackageReference Include="coverlet.collector" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" PrivateAssets="all" />
  </ItemGroup>

</Project>