<Project>
  <Import Project="..\Directory.Build.props" />

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(Configuration)' == 'Release'">net6.0;net7.0;net8.0;$(TargetFrameworks)</TargetFrameworks>

    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup Condition="$(ProjectName.EndsWith('Tests'))">
    <Compile Include="$(MSBuildThisFileDirectory)AssemblyInfo.cs" Link="AssemblyInfo.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'" >
    <PackageReference Include="coverlet.collector" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" PrivateAssets="all" />
  </ItemGroup>

</Project>