<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>AirRoutes for ExRam.Gremlinq!</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Core/ExRam.Gremlinq.Core.csproj" />
    <ProjectReference Include="../../analyzers/Testing.AirRoutes.Generators/ExRam.Gremlinq.Testing.AirRoutes.Generators.csproj" OutputItemType="Analyzer" PrivateAssets="all" />
  </ItemGroup>
  
</Project>
