<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Remove="**\*.verified.txt" />
    <None Remove="**\*.received.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" VersionOverride="3.52.1" />
    <ProjectReference Include="..\Tests.Fixtures\ExRam.Gremlinq.Tests.Fixtures.csproj" />
  </ItemGroup>

</Project>
