<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="PublicApiGenerator" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Providers.GremlinServer.AspNet/ExRam.Gremlinq.Providers.GremlinServer.AspNet.csproj" />
    <ProjectReference Include="../../src/Providers.Neptune.AspNet/ExRam.Gremlinq.Providers.Neptune.AspNet.csproj" />
    <ProjectReference Include="../../src/Providers.JanusGraph.AspNet/ExRam.Gremlinq.Providers.JanusGraph.AspNet.csproj" />
    <ProjectReference Include="../../src/Support.TestContainers/ExRam.Gremlinq.Support.TestContainers.csproj" />
    <ProjectReference Include="../Tests.Infrastructure/ExRam.Gremlinq.Tests.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Support.NewtonsoftJson.AspNet/ExRam.Gremlinq.Support.NewtonsoftJson.AspNet.csproj" />
    <ProjectReference Include="../../src/Testing.AirRoutes/ExRam.Gremlinq.Testing.AirRoutes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="*.verified.cs" />
    <Compile Remove="*.received.cs" />
  </ItemGroup>

</Project>
