<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Remove="Verifier\**" />

    <EmbeddedResource Remove="Verifier\**" />

    <None Remove="*.verified.txt" />
    <None Remove="*.received.txt" />
    <None Remove="Verifier\**" />

    <ProjectReference Include="..\..\src\Providers.GremlinServer\ExRam.Gremlinq.Providers.GremlinServer.csproj" />
    <ProjectReference Include="..\..\src\Support.NewtonsoftJson\ExRam.Gremlinq.Support.NewtonsoftJson.csproj" />
    <ProjectReference Include="..\..\src\Support.TestContainers\ExRam.Gremlinq.Support.TestContainers.csproj" />
    <ProjectReference Include="..\Tests.Infrastructure\ExRam.Gremlinq.Tests.Infrastructure.csproj" />
  </ItemGroup>

</Project>
