<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>TestContainers support library for Gremlinq.</Description>
    <GitBranch>$([System.IO.File]::ReadAlltext('$(SolutionDir)\.git\HEAD').Replace('ref: refs/heads/', '').Trim())</GitBranch>
    <IsPackable>false</IsPackable>
    <IsPackable Condition="'$(GitBranch)' == '12.x'">true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Providers.Core\ExRam.Gremlinq.Providers.Core.csproj" />
  </ItemGroup>


</Project>
