<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>TestContainers support library for Gremlinq.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers" />
    <ProjectReference Include="..\Providers.Core\ExRam.Gremlinq.Providers.Core.csproj" />
  </ItemGroup>

</Project>
