<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>TestContainers support library for Gremlinq.</Description>

    <IsPackable>false</IsPackable>
    <IsPackable Condition="'$(GitBranch)' == '13.x'">true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers" />
    <ProjectReference Include="..\Providers.Core\ExRam.Gremlinq.Providers.Core.csproj" />
  </ItemGroup>

</Project>
