<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>ExRam.Gremlinq.Templates</PackageId>
    <Description>'dotnet new' templates for ExRam.Gremlinq.</Description>
    <PackageType>Template</PackageType>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <LocalizeTemplates>false</LocalizeTemplates>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.TemplateEngine.Tasks" Version="*" PrivateAssets="all" IsImplicitlyDefined="true" />
    <Compile Remove="**/*" />
    <Content Include="console/**/*" />
    <Content Include="aspnet/**/*" />
  </ItemGroup>

</Project>
