<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>.NET object-graph-mapper for Apache TinkerPop™ Gremlin enabled databases.</Description>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net6.0' or '$(TargetFramework)'=='net7.0'">
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net6.0' or '$(TargetFramework)'=='net7.0' or '$(TargetFramework)'=='net8.0'">
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.HighPerformance" />
    <PackageReference Include="Gremlin.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Generator\ExRam.Gremlinq.Core.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
    <None Update="Queries/T4/TreeBuilder.tt">
      <LastGenOutput>TreeBuilder.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>

    <Compile Update="Queries/T4/TreeBuilder.cs">
      <DependentUpon>TreeBuilder.tt</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>
  
</Project>
