<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>.NET object-graph-mapper for Apache TinkerPop™ Gremlin enabled databases.</Description>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net6.0' or '$(TargetFramework)'=='net7.0'">
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.HighPerformance" />
    <PackageReference Include="Gremlin.Net" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" VersionOverride="9.0.8" />
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
    <None Update="Queries\T4\TreeBuilder.tt">
      <LastGenOutput>TreeBuilder.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>

    <None Update="Queries\T4\ProjectBuilder.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ProjectBuilder.cs</LastGenOutput>
    </None>
    <None Update="Queries\GremlinQuery.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>GremlinQuery.generated.cs</LastGenOutput>
    </None>
    <Compile Update="Queries\T4\TreeBuilder.cs">
      <DependentUpon>TreeBuilder.tt</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>

    <Compile Update="Queries\T4\ProjectBuilder.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProjectBuilder.tt</DependentUpon>
    </Compile>
    <Compile Update="Queries\GremlinQuery.generated.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GremlinQuery.tt</DependentUpon>
    </Compile>
  </ItemGroup>
  
</Project>
