<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="**\*.verified.txt" />
    <None Remove="**\*.received.txt" />

    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    
    <ProjectReference Include="..\..\src\Core.AspNet\ExRam.Gremlinq.Core.AspNet.csproj" />
    <ProjectReference Include="..\Tests.Infrastructure\ExRam.Gremlinq.Tests.Infrastructure.csproj" />
  </ItemGroup>

  </Project>
