<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>ASP.NET Core support package for ExRam.Gremlinq.Core.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <ProjectReference Include="../Core/ExRam.Gremlinq.Core.csproj" />
  </ItemGroup>

</Project>
