name: Benchmark

on:
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          global-json-file: global.json

      - name: Run benchmarks
        run: |
          cd test/Benchmarks
          dotnet run -c Release -- --filter '*' --exporters json --join

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@4bdcce38c94cec68da58d012ac24b7b1155efe8b # v1.20.7
        with:
          name: ExRam.Gremlinq Benchmarks
          tool: 'benchmarkdotnet'
          output-file-path: test/Benchmarks/BenchmarkDotNet.Artifacts/results/ExRam.Gremlinq.Benchmarks.QueryBuildingBenchmarks-report-full-compressed.json
          github-token: ${{ secrets.PUSH_TO_GH_PAGES_BRANCH_PAT }}
          auto-push: true
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: benchmarks
          #alert-threshold: '120%'
          #comment-on-alert: true
          #fail-on-alert: false
          save-data-file: ${{ github.event_name != 'pull_request' }}
