name: Check pull request

on:
  pull_request:
  workflow_call:

jobs:

  test-linux:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.fork || github.event.pull_request.title != 'Prepare release' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Build
      run: dotnet build  -c Release ./${{ github.event.repository.name }}.sln
      
    - name: Test
      run: dotnet test -c Release --no-build --collect:"XPlat Code Coverage;Format=opencover" ./${{ github.event.repository.name }}.sln 
      env:
        RunGremlinServerIntegrationTests: 'true'
        RunJanusGraphIntegrationTests: 'true'
        RunNeptuneIntegrationTests: 'true'

    - name: Collect coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  test-windows:
    runs-on: windows-2022
    if: ${{ github.event.pull_request.head.repo.fork || github.event.pull_request.title != 'Prepare release' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Start CosmosDb Emulator
      uses: janpio/cosmos-emulator-github-action@main
      with:
          parameter_string: "-EnableGremlin"

    - name: Build
      run: dotnet build  -c Release ./${{ github.event.repository.name }}.sln
      
    - name: Test
      run: dotnet test -c Release --no-build --collect:"XPlat Code Coverage;Format=opencover" ./${{ github.event.repository.name }}.sln
      env:
        RunCosmosDbIntegrationTests: 'true'
        
    - name: Collect coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}