name: Check pull request

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:

  test:
    strategy:
      matrix:
        os: [ ubuntu-24.04, windows-2025 ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      with:
        fetch-depth: 0
        submodules: 'true'
        token: ${{ secrets.CHECKOUT_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # 6.0.0
      with:
        global-json-file: global.json
        dotnet-version: |
          9
          8
   
    - name: Start CosmosDb Emulator
      if: ${{ matrix.os != 'ubuntu-24.04' }}
      uses: janpio/cosmos-emulator-github-action@8c35a1bfde25fc32234c163c044322af3f2e56e3
      with:
          parameter_string: "-Timeout 600 -EnableGremlin"

    - name: Test
      run: dotnet test -c Release --solution ./${{ github.event.repository.name }}.slnx --coverlet --coverlet-output-format opencover --ignore-exit-code 8
        --report-trx --report-gh

    - name: Collect coverage
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # 7.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}