name: Pack

on:
  push:
    branches:
      - \d+\.x
    tags:
      - \d+\.\d+\.\d+
  workflow_call:
    secrets:
      CREATE_RELEASE_PAT:
        required: true

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:

  pack:
    runs-on: ubuntu-24.04

    outputs:
      packageVersion: ${{ steps.nbgv.outputs.NuGetPackageVersion }}
      isPreviewRelease: ${{ startsWith(steps.nbgv.outputs.PrereleaseVersionNoLeadingHyphen, 'preview') }}

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      with:
        fetch-depth: 0
        submodules: 'true'
        token: ${{ secrets.CHECKOUT_TOKEN }}
        
    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # 6.0.0
      with:
        global-json-file: global.json
        dotnet-version: |
          9
          8

    - name: Determine semantic version
      uses: dotnet/nbgv@f088059084cb5d872e9d1a994433ca6440c2bf72 # 0.4.2
      id: nbgv

    - name: Replace NuGet version default value in templates
      run: find -name template.json -exec sed -i "s/TEMPLATE_GREMLINQ_VERSION_DEFAULT_VALUE/${{ steps.nbgv.outputs.NuGetPackageVersion }}/g" {} \;

    - name: Build
      run: dotnet build ./${{ github.event.repository.name }}.slnx -c Release -p:ContinuousIntegrationBuild=true

    - name: Pack
      run: dotnet pack ./${{ github.event.repository.name }}.slnx -c Release --no-build

    - name: Copy NuGet packages to artifacts
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # 4.4.0
      with:
        name: NuGetPackages
        path: './**/*Gremlinq*.nupkg'
        if-no-files-found: error

    - run: echo ${{ steps.nbgv.outputs.NuGetPackageVersion }} > Version

    - name: Output version to artifacts
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # 4.4.0
      with:
        name: Version
        path: Version
        if-no-files-found: error

  attest:
    if: ${{ needs.pack.outputs.isPreviewRelease == 'false' }}
    needs: [ pack ]
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # 4.1.8
      with:
        name: NuGetPackages
        
    - name: Attest build provenance
      if: ${{ github.event.repository.visibility == 'public' }}
      uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # 2
      with:
        subject-path:  './**/*Gremlinq*.nupkg'
    
  release:
    if: ${{ needs.pack.outputs.isPreviewRelease == 'false' }}
    needs: [ pack, attest ]
    runs-on: ubuntu-24.04

    steps:

    - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # 4.1.8
      with:
        name: NuGetPackages
        
    - name: Create release
      id: create_release
      uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # 6.1.0
      with:
        name: ${{ github.event.repository.name }} ${{ needs.pack.outputs.packageVersion }}
        tag: ${{ needs.pack.outputs.packageVersion }}
        commitish: ${{ github.ref }}
        publish: false
      env:
        GITHUB_TOKEN: ${{ secrets.CREATE_RELEASE_PAT }}

    - name: Upload assets
      uses: shogo82148/actions-upload-release-asset@aac270e08f6b4547ada0b3800f88e1eb3ce9d400 # 1.7.7
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path:  './**/*Gremlinq*.nupkg'
        github_token: ${{ secrets.CREATE_RELEASE_PAT }}
        

