name: Push preview packages

on:
  workflow_run:
    types: [completed]
    workflows: [Pack]
  workflow_call:
    secrets:
      PUSH_TO_PACKAGES_PAT:
        required: true
      DOWNLOAD_ARTIFACTS_PAT:
        required: true

jobs:
  push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # 4.1.7
      with:
        name: NuGetPackages
        github-token: ${{ secrets.DOWNLOAD_ARTIFACTS_PAT }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Push NuGet packages to GitHub packages
      run: dotnet nuget push **/${{ github.event.repository.name }}.*.nupkg
        --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        --api-key ${{ secrets.PUSH_TO_PACKAGES_PAT }}
        --no-symbols
        --skip-duplicate
