name: Push stable packages

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write # required for NuGet Trusted Publishing (OIDC)

jobs:
  push:
    runs-on: ubuntu-slim

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # 6.0.0
      with:
        dotnet-version: 10

    - uses: robinraju/release-downloader@a96f54c1b5f5e09e47d9504526e96febd949d4c2 # 1.11
      with:
        releaseId: ${{ github.event.release.id }}
        fileName: "${{ github.event.repository.name }}.*.nupkg"

    - name: NuGet login (OIDC -> temp API key)
      uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: Push NuGet packages to NuGet.org
      run: dotnet nuget push **/${{ github.event.repository.name }}.*.nupkg
        --source https://api.nuget.org/v3/index.json
        --api-key ${{ steps.login.outputs.NUGET_API_KEY }}
        --no-symbols
        --skip-duplicate
